require_relative "board"
require_relative "cursorable"
require_relative "display"
require_relative "nullpiece"
require_relative "player"
require_relative "piece"
require_relative "errors"
require 'byebug'
# require_relative "chess"
# require_relative "pieces/"
# require_relative "players/"
